vim.keymap.set('i', 'jj', '<Esc>')
vim.keymap.set('n', '<c-j>', '<c-w>j')
vim.keymap.set('n', '<c-k>', '<c-w>k')
vim.keymap.set('n', '<c-h>', '<c-w>h')
vim.keymap.set('n', '<c-l>', '<c-w>l')
vim.keymap.set('n', '<leader>3', ':vsplit<cr>')
vim.keymap.set('n', '<leader>4', ':ssplit<cr>')
vim.keymap.set('n', '<leader>qq', ':q<cr>')
vim.keymap.set('n', '<leader>ww', ':w<cr>')
vim.keymap.set('n', '<leader>wq', ':wq<cr>')
vim.keymap.set('n', '<c-d>', '<cmd> lua vim.diagnostic.open_float() <CR>')
vim.keymap.set('n', '<leader>e', ':Neotree toggle<cr>')

